#!/bin/bash

clear
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/xray/config.json")

if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
    clear
    echo "─────────────────────────────────────────"
    echo "      Renew VPN Account          "
    echo "─────────────────────────────────────────"                                        echo ""
    echo "You have no existing clients!"
    echo ""
    echo "─────────────────────────────────────────"
    echo ""
    read -n 1 -s -r -p "Press any key to back on menu"
    menu
fi

# Ambil daftar klien yang sudah diurutkan dan simpan dalam array
mapfile -t sorted_clients < <(grep -E "^### " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | sort | uniq)

clear
echo "─────────────────────────────────────────"
echo "    Renew VPN Account            "
echo "─────────────────────────────────────────"
echo ""
echo "   No.  User          Expired"
echo "─────────────────────────────────────────"
for i in "${!sorted_clients[@]}"; do
    printf "%3d)  %s\n" $((i+1)) "${sorted_clients[$i]}"
done | column -t
echo ""
echo "─────────────────────────────────────────"

# Input nomor dari pengguna
read -rp "Select number [1-${#sorted_clients[@]}]: " CLIENT_NUMBER

# Validasi input
if [[ -z "$CLIENT_NUMBER" ]] || ! [[ "$CLIENT_NUMBER" =~ ^[0-9]+$ ]] || [[ "$CLIENT_NUMBER" -lt 1 ]] || [[ "$CLIENT_NUMBER" -gt "${#sorted_clients[@]}" ]]; then
    echo "Invalid selection!"
    read -n 1 -s -r -p "Press any key to back on menu"
    menu
fi

# Ambil data dari array yang sudah diurutkan
client_entry="${sorted_clients[$((CLIENT_NUMBER - 1))]}"
user=$(echo "$client_entry" | awk '{print $1}')
exp=$(echo "$client_entry" | awk '{print $2}')

if [[ -z "$user" ]]; then
    echo "User tidak ditemukan!"
    read -n 1 -s -r -p "Press any key to back on menu"
    menu
fi

read -p "Expired (days): " masaaktif

if ! [[ "$masaaktif" =~ ^[0-9]+$ ]]; then
    echo "Input harus berupa angka!"
    read -n 1 -s -r -p "Press any key to back on menu"
    menu
fi

now=$(date +%Y-%m-%d)
d1=$(date -d "$exp" +%s)
d2=$(date -d "$now" +%s)
exp2=$(((d1 - d2) / 86400))

if [[ -z "$exp2" || "$exp2" -lt 0 ]]; then
    exp2=0
fi

exp3=$(($exp2 + $masaaktif))
exp4=$(date -d "$exp3 days" +"%Y-%m-%d")

# vmess
sed -i "/^### $user /c### $user $exp4" /etc/xray/config.json

systemctl restart xray >/dev/null 2>&1

clear
echo "─────────────────────────────────────────"
echo " VPN Account Was Successfully Renewed"
echo "─────────────────────────────────────────"
echo ""
echo " Client Name : $user"
echo " Added Exp   : $masaaktif days"
echo " Expired On  : $exp4"
echo ""
echo "─────────────────────────────────────────"
echo ""
read -n 1 -s -r -p "Press any key to back on menu"
menu